//? DOM Elements References
//=========================

export const actualLocationLabel = document.querySelector(".location__actual-location-wrapper__cityName")
export const autoLocateButton = document.querySelector(".location__search-wrapper__auto-locate-button")
export const islamicDateLabel = document.querySelector(".islamic_date")
export const gregorianDateLabel = document.querySelector(".gregorian_date")
export const footerYearLabel = document.querySelector(".actual-year")
export const fajrTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.fajr")
export const sunriseTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.sunrise")
export const dhuhrTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.dhuhr")
export const asrTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.asr")
export const maghribTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.maghrib")
export const ishaaTimeLabel = document.querySelector(".prayerTimeCard__prayerTime.ishaa")
export const locationSearchWrapper = document.querySelector(".location__search-wrapper")
export const locationBtn = document.querySelector(".location")
export const mainTimeLabel = document.querySelector(".timingContainer__timeDua__timeNow")
export const citySearchInput = document.querySelector(".search-for-city-input")
export const citiesListMatch = document.querySelector(".extracted-cities-list")
export const upcomingPrayerLabel = document.querySelector(".timingContainer__upcomingPrayer__prayerName")
export const countDownLabel = document.querySelector(".timingContainer__upcomingPrayer__remainingTime")